apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: test
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
  selector:
    app: echoserver
